name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKERHUB }}
          password: ${{ secrets.PWD_DOCKERHUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:mariadb"
          push: true
          tags: chrisattineos/repoimageattineos:mariadb
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:wordpress"
          push: true
          tags: chrisattineos/repoimageattineos:wordpress
          
     - 
        name: Deploy Docker to AWS (EC2)
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.3
        with:
          aws_access_key_id: 
          aws_secret_access_key: 
          aws_default_region: eu-west-3
          aws_ami_id: # optional
          ec2_instance_type: t2.micro
         
