name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKERHUB }}
          password: ${{ secrets.PWD_DOCKERHUB }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: checkout
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:mariadb"
          push: true
          tags: chrisattineos/repoimageattineos:mariadb
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:wordpress"
          push: true
          tags: chrisattineos/repoimageattineos:wordpress
          
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETKEY }}
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::256403541264:role/accessallwithuseradmincpatin
      - 
        name: Setup ARM64 EC2
        id: ec2-arm64
        uses: truemark/aws-ec2-run-instance-action@v5
        with:
          security-group-id: "sg-076459ca5bd094b2e"
          subnet-id: "subnet-060e898e0ef9de33d"
          image-id: "ami-05a8450aee7da05fb"
          instance-type: "t2.micro"
#          instance-profile: "TruemarkEC2RoleforSSM"
          region: "eu-west-3"
          # Name of the EC2 instance to be added to the tags
          name: "testgithub"
          user-data: |
            #!/bin/bash
            echo "hello world"
