name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: chrisattineos
          password: ${{ secrets.PWD_DOCKERHUB }}
          
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image mariadb
      run:  docker build . --file mariadb/Dockerfile --tag chrislab_mariadb:latest
    - name: Build the Docker image wordpress
      run:  docker build . --file wordpress/Dockerfile --tag my-image-wordpress
    - name: Push the Docker image mariadb on Docker hub
      run:  docker push chrisattineos/chrislab_mariadb/chrislab_mariadb:latest      
      
      
      
