name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKERHUB }}
          password: ${{ secrets.PWD_DOCKERHUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:mariadb"
          push: true
          tags: chrisattineos/repoimageattineos:mariadb
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:wordpress"
          push: true
          tags: chrisattineos/repoimageattineos:wordpress
          
      -
        name: install dependance
        run: |
          sudo apt install npm nodejs
          npm install
          npm run build && npm run package
          
          
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETKEY }}
          aws-region: eu-west-3
#          role-to-assume: arn:aws:iam::256403541264:role/accessallwithuseradmincpatin
      - 
        name: AWS EC2 Run Instance
        # You may pin to the exact commit or the version.
        # uses: truemark/aws-ec2-run-instance-action@2e57ddbdb8d585c939f3bb088cf45df4d7e5f10b
        uses: truemark/aws-ec2-run-instance-action@v5
        with:
          # Subnet ID to launch the instance in
          subnet-id: "subnet-060e898e0ef9de33d"
          # Security group to apply to the EC2 instance
          security-group-id: "sg-076459ca5bd094b2e"
          # Image ID to use for the EC2 instance. Also accepts default-arm64 and default-amd64 options
          image-id: "ami-05a8450aee7da05fb"
          # Instance type to use for the EC2 instance
          instance-type: "t2.micro"
          # Instance profile to use for the EC2 instance
          instance-profile: "ecsInstanceRole"
          # Volume size in GB to use for the EC2 instance
          volume-size: "8"
          # Associate a public IP address to the EC2 instance
          associate-public-ip-address: "false"
          # Tags to apply to the EC2 instance
          tags: "vmtestgithub"
          # Startup commands to run on the EC2 instance
          user-data: "sudo apt update -y"
          # Shutdown behavior for the EC2 instance. This may be stop or terminate.
          instance-shutdown-behavior: "stop"
          # AWS region to use for the EC2 instance
          region: "eu-west-3"
          # SSH key name to use for the EC2 instance
          key-name: "keypair1"
          # Terminate the EC2 instance after the post step
          terminate-on-post: "false"
          # Name of the EC2 instance to be added to the tags
          name: "vmtestgithub"
