name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image mariadb
      run: docker build -f mariadb/Dockerfile -t my-image-mariadb
    - name: Build the Docker image wordpress
      run: docker build -f wordpress/Dockerfile -t my-image-wordpress
