name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: chrisattineos
          password: CpA0709*CpA0709*
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image mariadb
      run:  docker build . --file mariadb/Dockerfile --tag my-image-mariadb:chrisattineos/repoimageattineos
    - name: Build the Docker image wordpress
      run:  docker build . --file wordpress/Dockerfile --tag my-image-wordpress:chrisattineos/repoimageattineos
    - name: Push the Docker image mariadb on Docker hub
      run:  docker push my-image-mariadb
