name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKERHUB }}
          password: ${{ secrets.PWD_DOCKERHUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:mariadb"
          push: true
          tags: chrisattineos/repoimageattineos:mariadb
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:wordpress"
          push: true
          tags: chrisattineos/repoimageattineos:wordpress
          
      -
        name: terraform-cdk-action
        uses: dflook/terraform-apply@v1.29.1
        with:
          # Path to the terraform configuration
          path: .
          # Name of the terraform workspace
          workspace: # optional, default is default
          # List of backend config values to set, one per line
          backend_config: # optional, default is 
          # Path to a backend config file
          backend_config_file: # optional, default is 
          # Variable definitions
          variables: # optional
          # Comma separated list of vars to set, e.g. 'foo=bar'
          var: # optional, default is 
          # List of var file paths, one per line
          var_file: # optional, default is 
          # Limit the number of concurrent operations
          parallelism: # optional, default is 0
          # A friendly name for this plan
          label: # optional, default is 
          # Automatically approve and apply plan
          auto_approve: true
